spring:
  datasource:
    url: jdbc:mysql://47.107.88.8:3306/device_manager?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: keanu
    password:
server:
  servlet:
    context-path: /homework
  port: 8080